export interface UranusEventDateDTO {
    id?: number
    event_id?: number
    release_status?: string
    start_date?: string
    start_time?: string
    end_date?: string
    end_time?: string
    entry_time?: string
    duration?: number
    all_day?: boolean
    accessibility_flags?: string
    accessibility_summary?: string
    accessibility_info?: string
    visitor_flags?: string
    street?: string
    house_number?: string
    postal_code?: string
    city?: string
    country?: string
    state?: string
    lon?: number
    lat?: number
    total_capacity?: number
    seating_capacity?: number
    building_level?: number
    venue_id?: number
    venue_name?: string
    venue_website?: string
    venue_logo_id?: number
    venue_light_theme_logo_id?: number
    venue_dark_theme_logo_id?: number
    venue_logo_url?: string
    venue_light_theme_logo_url?: string
    venue_dark_theme_logo_url?: string
    space_id?: number
    space_name?: string
    space_website?: string
}
